name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    env:
      working_directory: ./GoogleChart.Net.Wrapper
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET Core 3.1.404
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.404'
    - name: Setup .NET Core 5.0.100
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{env.working-directory}}
      
    - name: Install gpr
      run: dotnet tool install gpr --global
    - name: gpr upload
      run: find -name "*.nupkg" -print -exec gpr push -k ${{secrets.GH_PACKAGE}} {} \;
      
